### ISSUE TITLE
Show current/past related maintenance on Case page

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/alces-flight-center#121]
More of a UI issue - when we request maintenance for multiple components, we can currently only see the first component associated with the ticket. Could we make it so all components with maintenance pending/accepted are shown in the "Association" field for their respective tickets? 

Also, again a UI thing, could we possibly show which tickets have a component actually in maintenance and it's association separate? Otherwise you can't easily tell which tickets have a component under maintenance other than going to the "Maintenance" section - which doesn't necessarily say the ticket associated with the maintenance.

**Comment by bobwhitelock** [comment]
To summarize discussion at https://alces.slack.com/archives/C72GT476Y/p1521480950000190:

> More of a UI issue - when we request maintenance for multiple components, we can currently only see the first component associated with the ticket. Could we make it so all components with maintenance pending/accepted are shown in the "Association" field for their respective tickets?

We should show all current (and, ideally, past) maintenance for each Case on the Case page.

> Also, again a UI thing, could we possibly show which tickets have a component actually in maintenance and it's association separate? Otherwise you can't easily tell which tickets have a component under maintenance other than going to the "Maintenance" section - which doesn't necessarily say the ticket associated with the maintenance.

This is now close to how things are shown in the latest changes on `develop`, to be released in the near future. We just need to make sure we show ticket titles in some way in the maintenance table (split out a card for this at https://trello.com/c/lcqWAgVt/75-show-ticket-title-in-some-way-in-maintenance-table).

**Comment by jamesremuscat** [comment]
> We should show all current (and, ideally, past) maintenance for each Case on the Case page.

I think this is covered by #166.

**Comment by bobwhitelock** [comment]
I think this has all been addressed with recent maintenance UI improvements; can re-assess and see if any further improvements are needed once these have been deployed.
