### ISSUE TITLE
Integrate with metalware asset export files to create component inventory 

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#135]
Rather than entering asset information directly into flightcenter change our component models to be in line with metalware (either metalware model needs to look like flightcenters or vice versa - probably something in between) Flight center then needs to be able to import the information from a metalware export file every time it’s changed in metalware, and display that information for component selection, asset records etc.

**Comment by ste78** [comment]
Going to bring this forward, initially as an r&d project. Let’s try and work with @WilliamMcCumstie ‘s metalware assets in some way and see where it goes. Can discuss IRL for more detail in here..

**Comment by bobwhitelock** [comment]
Talk about later, Steve says I should do in several weeks.

**Comment by ste78** [comment]
dropping this from flightcenter and turning it into a R&D project. I feel a new product coming on 😬
