### ISSUE TITLE
Log page displaying repeated ticket/case ID's

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#187]
Historical log entries are showing with multiple links to the case they have been linked.

**Comment by ste78** [comment]
<img width="929" alt="screen shot 2018-04-29 at 18 09 41" src="https://user-images.githubusercontent.com/503613/39409081-a0905e08-4bd8-11e8-82cb-03f0171a9e68.png">

**Comment by bobwhitelock** [comment]
After redeploying the staging server afresh and re-importing the production data I can't reproduce this. If this ever was an issue I must have fixed it, but I think the most likely cause is that this was the first time we were deploying to staging and also importing modified production data, and so in the process of doing this either the import failed or I interrupted it. When this happened some already imported stuff, like the Case-Log join table, were kept around, causing some of these links to be duplicated. Now that I've figured out how to do the import in a repeatable way this shouldn't reoccur, but re-open this or a new issue if you ever see anything similar again.
