### ISSUE TITLE
Error when creating new case

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#192]
I'm having trouble replicating this but logging it anyway if we can check the logs - when logged in as admin i seem to be able to get my session into a state that i can no longer log tickets, instead I get the attached error message. To fix I have to log out and in again. (last got this 18:21 29/4/18)

**Comment by ste78** [comment]
<img width="525" alt="screen shot 2018-04-29 at 18 21 47" src="https://user-images.githubusercontent.com/503613/39409243-753ef86a-4bdb-11e8-8228-01eb331769fe.png">

**Comment by bobwhitelock** [comment]
@ste78 So after investigating I can't reproduce this, which is not helped by there no longer being any logs available from when this occurred.

I have seen the Case form app stop updating before when the selects are changed - did you notice that when this occurred? Possibly this could be the same issue - do you remember if you manually refreshed the page at all after getting into this state? If not it could be the same issue and Turbolinks is preserving the broken form in some way; if it is this then I don't think this is a new issue with the recent changes. If you did refresh, then I have no idea what this could be at the moment.

To help us diagnose this if it happens again, and as probably a good idea generally, I've set up Papertrail for both our production and staging apps. So if anyone including a customer gets this issue we should be able to dig in slightly more to see what's going on.

I'll leave this open for now and we can look into it with more info available if it does happen again.

**Comment by ste78** [comment]
okies, sounds good. I'll update this ticket with time&dates if I get it again..

**Comment by ste78** [comment]
not seen this since, lets say it no longer happens :)
