### ISSUE TITLE
Comments loose new lines etc

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#199]
When entering a comment, if you do something like 
```
Hi

Do things

Kind Regards

Steve
```

It comes out as `Hi Do things Kind Regards Steve`. Both in the web interface and emails. 

Can we do something to make it keep basic newlines / formatting as entered by the user?

**Comment by mjtko** [comment]
Perhaps we could render both the longer input fields (e.g. "Steps to replicate issue") and the comments as markdown?

Might complicate emails slightly tho, so if it's easier just to preserve line breaks for now let's go for that.
