### ISSUE TITLE
Tier 2 user prevented comments

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#202]
When a user views a tier 2 ticket, the comment box is rightly greyed out. However the only way you know why is to hover over it. Is it possible to have a box showing why they are not able to do this more clearly?

**Comment by mjtko** [comment]
Or don't show the comment box/button at all.

It feels like this is quite an uncomfortable interaction between customer and support team. If they haven't logged enough details I'm not quite sure how we go about getting enough.

Doing a "resolve" ("reject") and getting them to open a new one by telling them they didn't provide enough detail first time around feels a bit abrasive.  I think this interaction will need iterating on.

**Comment by bobwhitelock** [comment]
Decision: do what Steve says.

**Comment by jamesremuscat** [comment]
See also https://trello.com/c/oSqqaXvS/250-make-it-more-obvious-why-non-consultancy-cases-cannot-be-commented-on
