### ISSUE TITLE
Archive case page cleanup

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#206]
Not sure how the archive page is. supposed to work, but what’s it’s. now doing does seem a. little confusing - it seems to be displaying all cases including archived. Think this could do with a bit of a cleanup functionality wise. 

I suggest.. 

- rename so archive page becomes a ‘resolved’ page which shows resolved and archived cases
- open cases are not shown

**Comment by mjtko** [comment]
At some point we talked about renaming "Archived" to "Completed", can't find where this was logged tho.

Our states were something like:

Open (logged/being worked on)
Resolved (work complete/happy customer)
Completed (logged in credit reports process)

As far as customer is concerned:

Open (logged/being worked on)
Resolved (work complete/happy customer)

Customer should be able to see Resolved cases - they don't need to know if it's been "Completed" or not.

**Comment by bobwhitelock** [comment]
Decisions:

- rename `archived` state to `closed`;

- have `/archives` page show just `resolved` and `closed` cases;

- call `/archives` page `/resolved`.
