### ISSUE TITLE
Flight Center version display

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#207]
I guess flight center has a version or tag or something? we should consider putting this in the footer so we know which version we are testing.

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/u07sGH6U/174-flight-center-version-display

**Comment by bobwhitelock** [comment]
Brief idea for how to do this: in `alces:deploy:*` Rake tasks, after successfully deploying app set an environment variable in Dokku with same tag as pushed to GitHub; this can then be grabbed by the app and displayed in the footer (or wherever).
