### ISSUE TITLE
Consider allowing reopening Cases, and how this should work

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#208]
If a case has been accidentally closed, there is no way to reopen it via the UI, and I'd be nervous manipulating the database to do so.

Can we have a "reopen" button for cases that have been marked as "resolved" but are not yet "completed" (or, as using current nomenclature "archived")?

**Comment by mjtko** [comment]
This is primarily to cover somebody accidentally resolving something they didn't mean to -- I know there's a confirmation dialog, but that doesn't mean it won't happen. :-)

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/A3tbOsLg/173-consider-allowing-reopening-cases-and-how-this-should-work

**Comment by ste78** [comment]
so this is probably required after living with the new tiered system for a while. 

My thoughts:

- Have a re-open button available to users as well as admins
- only resolved tickets can be re-opened (not closed) 
- only allow re-opening with a comment
- tier0-2 cases automatically become a tier 3 case when re-opened, the usual ticket escalation warning about charges should be given.

**Comment by mjtko** [comment]
Some further thoughts -- this could be part of the "accept/reject resolution" workflow:

* "Reject" would effectively be the same as "reopen" as @ste78 has described i.e. "reopen with comment as to why this resolution has been rejected"
* "Accept" would be "yes, this can be closed"

It also occurs to me that, if we were to go with this kind of workflow, we should probably do auto-accept after, say, 5 working days to prevent having to chase up site contacts to accept.

(I can think of a number of later extensions to this, but that's a start point for discussion.)

Do we need to escalate in this scenario?  I'd expect the admin to escalate/open for comments in response if further discussion is necessary. Or the user to explicitly escalate if they feel they need further dialog.

**Comment by bobwhitelock** [comment]
@mjtko That sounds like it could work well for both use cases - had a quick look and came up with the following, is this how you imagine the workflow:

![case_state](https://user-images.githubusercontent.com/7476523/41382049-4ec8632e-6f62-11e8-84dc-80d4ba5d6bfc.png)

(For anyone's future reference the code changes used here are in https://github.com/alces-software/alces-flight-center/commit/83c6d42b563c8bbbcc264a50751d56b4bed3842a, and the diagram was generated using `rake state_machines:draw CLASS=Case`).

> Do we need to escalate in this scenario? I'd expect the admin to escalate/open for comments in response if further discussion is necessary. Or the user to explicitly escalate if they feel they need further dialog.

I agree, this seems like an orthogonal concern - I can imagine many situations where we think we've fixed something but later realise/are prompted by a user that this doesn't fix the original issue and so need to re-open the Case, but other than that there is not necessarily any need to escalate the Case.

**Comment by ste78** [comment]
yep makes sense, we need to be careful with the wording on 'reject, accept' buttons though.. ie something more like

"Yes this have resolved my issue. Thanks!"
"No I am still having difficulty"

and "User response period elapsed, ticket automatically resolved."

I'll accept out-voting on the escalate at the same time issue, my thoughts we're if its not as straightforward as we originally suspected its a tier3, but agree we can do this second stage once its reopen.

**Comment by mjtko** [comment]
@bobwhitelock - looks good!  Agree the wording should be friendly.

State-name-wise, maybe we could use "resolved" - i.e. admin thinks they've resolved it - and "fixed" (or maybe "verified"?) - i.e. user accepts resolution as having fixed the issue.

"User acceptance period elapsed, case automatically completed."?

I think mandatory escalation would potentially head-off some undue conversation, so if that starts happening, we should probably revisit the process.
