### ISSUE TITLE
No need for emails on case (re)assignment

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#212]
When a case is assigned to a user/admin an email is sent out.  I don't think we need to send out an email in this case.

Possibly in future we might want "assign & comment" or something, but it's a bit noisy at the moment to send out emails when a case is assigned.

**Comment by bobwhitelock** [comment]
Decision: instead, on assignment change email just the person who was assigned (and tickets mailing list as we always do).
