### ISSUE TITLE
Reassignment emails contain wrong assignment details

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#213]
Though I'm not convinced of the utility of the assignment emails as a whole, they should contain the correct details.  It appears they show the name of the user who performed the reassignment operation rather than who they are assigned to, e.g. I assigned #176 to Ruan, and then Steve, and both times I got an email saying:

> This case has been assigned to Mark Titorenko (previously assigned to Mark Titorenko).

**Comment by bobwhitelock** [comment]
To add to this, I got some similar issues on Friday:

- I got the 'no user assigned email' when I first assigned a User to a Case.

- I got the 'assigned to $user' email when assigned a Case with a User already assigned to nobody - I think the `$user` in this case was the user who was previously assigned.

**Comment by bobwhitelock** [comment]
This was fixed in #215 I believe (please re-open if I'm mistaken).
