### ISSUE TITLE
Asset data entry / refactor

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#22]
We'd like to be able to create / edit component Asset records from the flight center interface (rather than the admin interface). 

Some preliminary thoughts...

- Only admins should be allowed to set / edit asset records
- All other users can view the data as entered
- Group level and component level data entry / override should be possible
- On the cluster view dashboard, there are already view links to view more information on the individual assets, I'd imagine similar links being available for the actual component group name as well to allow viewing / editing of group data.
- The existing component view / component group view page would also allow editing the fields with a save/update button if the logged in user is an admin, otherwise a formatted view page is shown for everyone else
- If a component asset record field is empty, its should be overridden by what is set for the field at the group level.
- We'd like to implement a new 'Asset Type' model, that would contain some pre-compiled data about the component and would be selected from a drop down list when setting up a component / component group. We'd need minimum:
  - Type (fixed selection from the component types model: sever / switch / disk array / vm)
  - Manufacturer (text entry eg: 'Dell')
  - Model (text entry eg: 'Dell R720xd')
  - Knowledgebase URL: (text entry eg: 'https://github.com/alces-software/knowledgebase/wiki/server-dell-rseries-r720')
  - Expansions (also a new model of type (network, disk controller, psu), slot (int) and number of ports (int)
- When editing a component group, only the Asset Types, matching the component type for the selected component group would be shown. 
- Asset Types can only be selected for component groups, but displayed as view only on the Component page. (it makes no sense to have different Asset Types in a component group).

Also I'd like to cleanup the fields for each component type: 

SERVER
Group level set:
-Asset Type (selection from asset types)
-Firmware revision, text box, 50 characters
-Management username, text box, 50c
-Management password, text box, 50c
-Management Netmask, text box, IP
-Management Gateway: text box, IP
-BIOS Profile: text box, 50c
-BIOS exceptions: text area, 500c
-Internal disk setup: text area, 500c
-Additional expansions
Component level set:
(All group level fields are visible but not editable)
- hostname: text box, 50c
-Serial number, text box, 50c
-Management IP, text box, IP
-Physical labels applied

NETWORK 
Group level set: 
-Asset Type (selection from asset types)
-Firmware revision, text box, 50 characters
-Management username, text box, 50c
-Management password, text box, 50c
-Management Netmask, text box, IP
-Management Gateway: text box, IP

Component level set: 
-Serial number, text box, 50c
-Management IP, text box, IP
-Physical labels applied

DISK ARRAY:
Group level set: 
-Asset Type (selection from asset types)
-Firmware revision, text box, 50 characters
-Management username, text box, 50c
-Management password, text box, 50c
-Management Netmask, text box, IP
-Management Gateway: text box, IP

Component level set: 
-Serial number, text box, 50c
-Management IP, text box, IP
-Physical labels applied

VIRTUAL MACHINE:
Group level set: 
-Asset Type (selection from asset types)
-Hosts (selection from another server type component, one or more)
-Disk setup

Component level set: 
- hostname: text box, 50c

**Comment by bobwhitelock** [comment]
From discussion with William and looking at the original requirements, the following should sum up everything which still needs doing to complete this issue (aside from the PRs currently under review):

- [ ] Handling validation when the asset record form is submitted, and appropriately displaying any errors in the form.

- [ ] Disabling fields which cannot be set at this level when editing an asset record, and indicating via `title` text why this is the case (similarly to is already done currently in the admin interface).

- [ ] Displaying placeholders when a value has been set at a higher level, and only pre-filling a field with the value set at this level.

- [ ] Displaying a select box to switch the `ComponentMake` for an asset:
	- this should only display the `ComponentMake`s for the asset's `ComponentType`;
	- it should only be editable on the `ComponentGroup` asset record edit page;
	- related to this, we'll also want to show the `ComponentMake` and its fields on the `Component` and `ComponentGroup` pages, which we currently don't do; I'm not sure what the best way of showing this is right now.

- [ ] Adding some kind of `data_type` field to `AssetRecordFieldDefinition`s:
	- this should indicate what kind of data can be entered for a field, as well as the validations that will run;
	- for the first pass I think we'll need the following types:
		- `short_text` - display as text input;
		- `long_text` - display as text area;
		- `ip` - display as text input with indication that this should be an IP; validate it is an IP server-side (the [`IPAddr` class](http://devdocs.io/ruby~2.4/ipaddr) may be useful for this, it should raise an error for an invalid ID string);
		- `hosts` - this is only needed for VMs at the moment, and should allow specifying any number of hosts for a group of VMs - since this form will only be accessible to admins we may be able to get away with a slightly bad UI for the first pass, and client-side just provide a text input which says it needs a comma-separated list of node names. Server-side we can then just split this string and look up the `Component` with each name in the `Cluster` components; if any `Component` can not be found then this can just be  an error to be displayed in the re-rendered form.
		
			I'm not sure how we should save this field at the moment, we may need to have an optional additional one-to-many relation between `AssetRecordField`s and `Component`s.
		
			Since this field will be comparatively a lot of work to implement well, maybe we can skip it for the first pass of the feature - worth discussing with Steve.
	- we will also need to migrate the existing database to add these types, and change the `AssetRecordFieldDefinition`s as specified in the original post.
	
- [ ] We also need to handle how displaying/editing of expansions at the component/group level should work - this is probably worth revisiting once the above points have been completed sufficiently.

@WilliamMcCumstie hope this is useful to give you an overview of the next steps, let me know if anything's unclear :slightly_smiling_face:.

**Comment by bobwhitelock** [comment]
From meeting:

- VM `hosts` should always be a relation to a `ComponentGroup`;

- want to add table of all `Component`s in group on `ComponentGroup` page - similar to existing cards showing this on `Cluster` page;

- for expansions, show and allow editing (including adding and deleting) of expansions on `Component` page;

    - then come back and look at this and consider how we should allow bulk edit of `Component` expansions, as well as other asset record fields (like serial numbers).

**Comment by bobwhitelock** [comment]
This has now been completed and was released in https://github.com/alces-software/alces-flight-center/releases/tag/2018-02-08. Please open new issues for any improvements to/issues with the current implementation.
