### ISSUE TITLE
Add Component logs

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#23]
We'd like to add a service record to each component page, editable only by alces admins, but viewable off each component by the user.

A service record page would show each service record entry and allow new service records to be added. 

A service records is

Date/Time entered | Engineer (alces admin who added the record) | Details (enough for a brief description but keep the page fairly neat) | Related Ticket Numbers

**Comment by bobwhitelock** [comment]
- call 'Component log'

- still show on cluster log page, but also on individual component page
