### ISSUE TITLE
Cluster Log page

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#24]
We'd like to add a cluster log page, editable by alces admins, viewable by others. It would consist of a page linkable from the cluster management page where a user can view log entries created by alces admins. 

Starting fields..
Date/Time entered | Engineer (alces admin who added the record) | Details (enough for a brief description but keep the page fairly neat) | Related Ticket Numbers

eg
2018-01-01 00:00 | Steve Norledge | Restarted PITA service | 11984, 11985 |

**Comment by bobwhitelock** [comment]
Done in https://github.com/alces-software/alces-flight-center/pull/64. @WilliamMcCumstie if you mention the issue number with closes (e.g. `closes #123` then it will auto-close the issue when it's merged :slightly_smiling_face:.
