### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#246]
(1) Post a message to our #support channel every time we send out a message to tickets@alces-software.com

(2) Post a message to our #support channel on every cluster log update

Highlight which cluster the post is for in the message so it can be easily filtered in the channel

**Comment by mjtko** [comment]
IMO, send it to the cluster-specific channel, though I guess it depends on how spammy it appears/becomes. #support is generally a spammier target (cf. Nagios).

**Comment by ste78** [comment]
I'm wanting to kill off all the specific cluster channels, theres gonna be too many to keep track of. If its to spammy, we'll need to cleanup what we are sending to it because nothing should be ignored.

**Comment by bobwhitelock** [comment]
@mjtko I agree, and that also would allow people to only subscribe to channels for clusters they are interested in. I guess (1) vs (2) is mostly an implementation detail, with (1) just being marginally more work to set up when creating a Cluster but also being a bit more explicit (and so possibly less likely for things to go wrong in future).

**Comment by bobwhitelock** [comment]
Alternatively I should just listen to Steve :man_shrugging:

**Comment by ste78** [comment]
all people should be interested in all sites, we don't have favourites :)

**Comment by ste78** [comment]
email so 2017

**Comment by mjtko** [comment]
I'd argue that a single channel containing all that information is harder to keep track of, and multiple channels are the natural way to filter per-cluster stuff rather than a search, but I guess it depends on how you Slack.

Agree that there should be no favourites. 😄

**Comment by ste78** [comment]
<img width="505" alt="screen shot 2018-05-11 at 11 46 07" src="https://user-images.githubusercontent.com/503613/39920961-fe2aca94-5510-11e8-8470-8718189876c2.png">

**Comment by mjtko** [comment]
Ok, consensus reached then -- let's not start using threads though, they're awful. :)

**Comment by ste78** [comment]
Also to avoid accidental freakouts we should highlight if the updates are from staging or I'd be up for sending staging ones to a different channel if its fairly straightforward

**Comment by bobwhitelock** [comment]
@ste78 Would probably make sense to have the channel come from an environment variable anyway when we implement this, so we should be able to just set that to a different value for staging.

**Comment by ste78** [comment]
sounds good

**Comment by bobwhitelock** [comment]
This was done in https://github.com/alces-software/alces-flight-center/pull/332, and we're adding onto that as needed as we also add new email types or otherwise want to notify Slack about a new event, therefore this has been done.
