### ISSUE TITLE
Maintenance is nearing completion notification

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#248]
We need to alert admins if maintenance sessions are nearing completion (eg an hour away) so they get prompted to act accordingly (extend with reasons or get on with fixing the issue). I'm open to ideas on how best to implement this..  

Going forward we'll want to alert admins if cases are staying open for more than 2days without update so that may have an influence on the implementation.

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/U0W6FE23/169-maintenance-is-nearing-completion-notification

**Comment by bobwhitelock** [comment]
Was done in https://trello.com/c/U0W6FE23/316-maintenance-is-nearing-completion-notification
