### ISSUE TITLE
Change self managed error text

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#250]
currently when attempting to logging tickets against self managed components/services you get:

<img width="631" alt="screen shot 2018-05-11 at 16 10 10" src="https://user-images.githubusercontent.com/503613/39931701-139d3bee-5536-11e8-8786-ed69126a429c.png">

Can that say:

`Logging tier 0-2 cases for a self-managed service/component is not available.`

**Comment by bobwhitelock** [comment]
Do you want this change backported so it's available in the current staging site (without merging all recent changes in)?

**Comment by bobwhitelock** [comment]
Steve says having these in next release is fine.
