### ISSUE TITLE
Sentry not reporting errors from non-web containers 

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/alces-flight-center#257]
When #256 occurred this was not reported to us without checking the logs, as this happened in the `flight-center-staging.resque.1` container; we should set things up so Sentry reports errors in this case (and possibly the same happens for other containers, like those for cron jobs?) so we get notified about this sort of issue in future.

**Comment by jamesremuscat** [comment]
https://github.com/getsentry/raven-ruby/issues/364 suggests that this might be not entirely trivial, though it's hard to tell from the level of detail given (and it's quite an old issue).

**Comment by jamesremuscat** [comment]
See also https://github.com/gocardless/resque-sentry
