### ISSUE TITLE
Cluster Check Register

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#26]
Placeholder for 2018.1 feature - I'll add more shortly....

**Comment by ste78** [comment]
The engineering team run thru daily checks of each cluster. Currently they use a spreadsheet to record. the results, i’d like an initial page for each cluster that shows a list of default checks and any additional cluster specific checks that have been defined, stores for each day the result (pass,pass with comment,escalated to case ID,or not applicable) and the engineer that set the result. 

admins can set results, add checks etc
users can view today’s or historical check results

**Comment by bobwhitelock** [comment]
From meeting:

- Need default set of checks, create for each (managed) cluster and can add and remove.

- See https://docs.google.com/spreadsheets/d/1JFcEEJUjGVY0y9w0-50dh0qWHwjfj3hab1hckndGfD8/edit#gid=0 for example of current checks.

- Checks in groups, depending on group of nodes, scheduler etc, consider later how best to implement.

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/svyEqsUw/46-cluster-check-register

**Comment by bobwhitelock** [comment]
From new meeting:

- in response to failing entries should create a log entry with what happened/what we did to fix;

- above still relevant;

- need to consider and decide how to implement.

**Comment by atoghill** [comment]
With the merging of #464 the initial implementation for this is now in `develop`, so I am closing this issue
