### ISSUE TITLE
Tier 2 - New User Request, no field for User ID

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/alces-flight-center#290]
Currently there is no box to be able to provide a User ID # in the Tier 2 ticket - New User Request. The customer will need to provide the UID that is used on their system, in the case of ticket BAR1, the customer had used the field for Linux Group to be able to enter that data. Certain scenarios do not require a UID, so the box should be optional, or even maybe in future we should have it as an option which is selected on a per-cluster basis?

**Comment by bobwhitelock** [comment]
Thanks for reporting - already noticed by Steve, and fixed by me in production :slightly_smiling_face:
