### ISSUE TITLE
Credit usage summary

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#296]
I can’t remember what we’ve already implemented with allocating credit to existing sites/cluster but I do remember us deciding to ignore that when implementing credit charges per case and look into it later. It’s time to look into it later 😬

Basically we want to see at any point how many credit are available, how many are used, and what they were used on. We should discuss IRL and update here with whatever we come up with as being the next step..

**Comment by bobwhitelock** [comment]
- Need running total per cluster of credits (possibly add back `CreditDeposit`s and related code);

- credits for a cluster can go negative;

- admins need to be able to add credits for a cluster, doing this via rails-admin interface is fine;

- ideally credit usage should be displayed in quarters, 3 month periods (Jan + Feb + March, April + May + June etc);

- later may go monthly but keep quarterly for now;

- come up with design and run past Steve.
