### ISSUE TITLE
New type of user - View only

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#301]
We need to sign up accounts for people that are able to view everything the current users can but not actually create tickets or change anything. 

They'd also be added as an additional email contact to all email communication about that site.

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/RrINOYEJ/335-new-type-of-user-view-only

**Comment by bobwhitelock** [comment]
@ste78 didn't get a chance to discuss this with you yesterday but it mostly seems fairly straightforward what you're asking for.

Briefly, my current plan for this is:

- we will have 4 distinct kinds of Users (people who can log in) now: `admin`, `primary_contact`, `secondary_contact`, `viewer` (the middle 2 are functionally identical atm, but might as well distinguish them here);

- the new User type, `viewer`, will be able to see everything and be sent all emails that a Site contact would, but will not be able to interact with anything in the site apart from navigating.

A few questions:

- Is this accurate?

- Anything additional needed to this?

- When displaying parts of the site that contacts will be able to interact with and viewers can't (e.g. the create case entry in the Cases dropdown, the escalate button on a Case page), do you want us to not show these things at all, or should they be shown but appear disabled (possibly with title text indicating why)? Either of these should be about as complex to do; if you don't have a strong preference for which then I'd lean towards the latter as it will make it clearer to viewers what features their Site contacts have access to.

**Comment by ste78** [comment]
- yep that’s accurate! 
- no, that’s it! 
- agree with you, disabled buttons sounds good.
