### ISSUE TITLE
Allow admins to enable / disable user communication box on a tier 1/2 case 

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#319]
Problem:

- User logs tier 2 issues
- Admin needs more information and ask the user a question
- User needs to be able to respond but keep the case as a tier 2

Suggested Workflow:

- Customer logs tier 2 case
- Admin confirms a valid tier 2 issue, asks the question and elects to enable 2 way communication
- User can see somewhere on the case page that the tier 2 case is authorised for two way communication and can put stuff in the comments box.

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/kcUUpdIh/188-allow-admins-to-enable-disable-user-communication-box-on-a-tier-1-2-case
