### ISSUE TITLE
blockquote tag in email confuses Airmail email client

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#335]
I use [Airmail](http://airmailapp.com/) which is a popular email application on MacOS.

The Flight Center emails don't always display correctly (see attached).  This seems mainly to do with the fact we're using `blockquote` which it's interpreting as an instruction to fold up the content as if it were from a previous email.

The content can be unfolded, though frequently this causes the email rendering to break entirely and display as blank.

Could we try changing the template to use a styled `div` or `p` instead?

(See [#alces-flight-center for some related screenshots](https://alces.slack.com/archives/C72GT476Y/p1528274758000450).)

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/VoWTgepK/348-blockquote-tag-in-email-confuses-airmail-email-client

**Comment by mjtko** [comment]
I have confirmed that this is fixed.  Ta!
