### ISSUE TITLE
Feature Request - Show associated maintenance in case view

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/alces-flight-center#368]
Probably an @jerrytheleprechaun feature request. Could we possibly show any maintenance associated with a case within the case view? Probably just a brief view of any maintenance currently active/pending that's associated with the case in the table at the top of the case view page. 

Maintenance is always associated with a case - so when dealing with cases, being able to see what maintenance is associated would be very beneficial, since currently it is possible to respond and resolve a case without realising that the component is within maintenance if you're coming to a ticket first hand.

**Comment by jamesremuscat** [comment]
You mean, more than we already do?

![selection_025](https://user-images.githubusercontent.com/3471844/41655613-452b4dea-7485-11e8-85f6-7d863c9b8b9b.png)

**Comment by RuanEllis** [comment]
You can see the maintenance that's in progress on the component associated to the ticket, however you have to scroll all the way down and read through the entire case history to see this, there could have been multiple responses whilst the node was in maintenance, therefore the _current_ status of the maintenance is unknown, other than reading back through the history. 

Having this visible from the case view page would be hugely beneficial to me - as it's difficult to keep track of all maintenance and know when maintenance is going to end, since currently the only way to know this is to go to the maintenance page and have to navigate to each ticket in turn. Having this viewable on the case view would help me hugely to be able to see at a brief glance, that a component is in maintenance and is due out of maintenance at some point in the future.

Simply the addition of this: 

<img width="265" alt="screen shot 2018-06-20 at 12 42 15" src="https://user-images.githubusercontent.com/8808600/41656500-13c2995e-7488-11e8-899c-b039459167fe.png">

Onto the case view page would help me massively with seeing the status.
