### ISSUE TITLE
Don't distinguish between primary/secondary site contacts in brand bar

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#373]
With the introduction of viewers, we now display the user's role in the brand bar.  I'm not sure what displaying the role adds to the UX (though, perhaps it could be handy to display when a user is a viewer to manage their expectations [the UI is already pretty good at this tho!]) and I don't think it's necessary to distinguish between primary and secondary site contacts.

Please can we either drop the "primary contact" and "secondary contact" terms entirely or, if we have to have something, use "site contact" for both?  Or drop the role from the brand bar entirely.

**Comment by bobwhitelock** [comment]
This was mostly useful when developing to quickly check what the `role` of the current user was when switching between various users; fbm if we want to drop it, or alternatively could be worth just adding an `if Rails.env.development?` to only show it in development.

**Comment by mjtko** [comment]
Sure, ok, let's leave it enabled for development and remove it elsewhere.
