### ISSUE TITLE
Minor text changes.

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#382]
`Additional discussion is not available for cases in the current support tier. If you wish to request additional support please either escalate this case (which may incur a charge), or open a new support case.`

to

`Additional discussion is not available for this case. If you wish to request additional support please either escalate this case, or open a new support case.`

And...

`Escalating this support case may incur charges

Escalating a support case means that the case becomes potentially chargeable, and may incur a charge of support credits.

Do you wish to continue?`

to

`Escalating a case, please note. 

Escalating a support case means that you authorise potential use of available account credit to help resolve your issue. 

Do you wish to continue?`

**Comment by ste78** [comment]
also

`Creating a support case at this tier is potentially chargeable, and may incur a charge of support credits. Click here for the charging details for this cluster.`

to 

`Creating a support case at this tier means that you authorise potential use of available account credit to help resolve your issue.. Click here for the credit usage details for this cluster.`

**Comment by ste78** [comment]
also

`This support case may incur charges

Creating a support case at this tier is potentially chargeable, and may incur a charge of support credits.

Do you wish to continue?`

to
 
`
Please note

Creating a support case at this tier means that you authorise potential use of available account credit to help resolve your issue.

Do you wish to continue?`

**Comment by jamesremuscat** [comment]
Implemented in #383.
