### ISSUE TITLE
Show pending count for resolved but unclosed tickets on credit usage page

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#389]
Current behaviour: resolved but unclosed cases are not displayed (as they are unclosed and don't have a credit usage/non-usage allocated to them).

Desired behaviour: a count of tickets that have been resolved but are pending closure.

Reasoning: this would be a useful number to display as it shows that there is activity in the current quarter regardless of whether cases have yet been closed.  The cases themselves should not appear in the list, but perhaps the number (or a link nearby) could link to the resolved cases list?

**Comment by jamesremuscat** [comment]
Should this figure be given per quarter, or as an absolute?

e.g. "number of cases with a resolution date in the currently selected quarter that have not yet been closed"

or

"number of cases in state "resolved"

Implementation hints:

The latter is easier, but that overall figure doesn't belong in the "Usage for Q*x*" box with the others; perhaps under the credit balance (but above the admins' credit deposit box).

The former will require adding an extra Rails scope to `Case`s on their resolution date (which I suspect will be a slightly complicated ActiveRecord `joins` query).

**Comment by mjtko** [comment]
I think the latter if it's significantly easier - not too concerned about cases that aren't closed from previous quarters (cos there shouldn't be any, or at least, very few and not for long after the quarter rolls over).

I agree that this information is better situated in the left-hand pane alongside the credit balance and the service plan term dates (ref: #403).

**Comment by mjtko** [comment]
Fixed via #500.
