### ISSUE TITLE
Usage report shows '-1 credits' when a single credit is charged

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#390]
There's a pluralization issue, but also I think this should simply say "1 credit" as it's obvious from the fact it's against a case that it's a charge, and it's in orange.

**Comment by jamesremuscat** [comment]
To clarify, you're asking that all the values on the credit usage report should be reported as positive?

The pluralization is a case of "Rails knows best, reality be damned" (Rails pull request 6533, if you're interested - not linking it to avoid Github's reverse-link magic happening).

**Comment by mjtko** [comment]
Yup, I think absolute values are fine as the context is sufficient to see it's a debit rather than a credit (of credits ;-)).

**Comment by DavidMarchant** [comment]
sorted with #463 :)
