### ISSUE TITLE
Add time-to-response to credit usage reports

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#392]
Our current reporting system includes time-to-first-response as a metric against each ticket to demonstrate our operation is within the agreed response times specified in our SLA.

In order to migrate away from the existing manual spreadsheet processes for Flight customers, we need to include this metric in the credit usage reports.

Aside: time-to-resolution might also be nice to have, but it might make the display of the report too congested (however, definitely worth recording from now, or at least having an idea of how we would generate that data retroactively as I think it's something we'll want to display somewhere in the future).  Open to ideas on this.

**Comment by mjtko** [comment]
Take into account working day length and ignore weekends (and, ideally, bank holidays) as the current process does.

**Comment by jamesremuscat** [comment]
In this context a "response" is "a comment posted by an admin" (making other changes to the case does not count as responding).

In the event that the case was raised by an admin, assume time-to-response is zero.

There are a number of options for how to display this; I suspect the most straightforwardly easy way is to add it to each charge event card on the credit report page (playing with the CSS flex settings to keep fields aligned).

We could also consider aggregate stats, such as mean time-to-response for the chosen reporting period, if we wanted to? Perhaps best left as future work?

We already store enough data to compute a time-to-resolution (date/time case is opened, and date/time case is resolved) so we don't need to do too much until we decide to start showing it.

**Comment by DavidMarchant** [comment]
@jamesremuscat @mjtko in the case that there are no admin comments on the case would you want the time to resolution to be output, the output to be left blank or something else entirely? (not sure who to @ here)

**Comment by jamesremuscat** [comment]
@DavidMarchant Either blank or `N/A`, and I think I slightly prefer `N/A` (unless @mjtko thinks differently).

Our process means that we _should_ never encounter this situation, but you're wise to have it covered :slightly_smiling_face:

**Comment by DavidMarchant** [comment]
@jamesremuscat Ok cheers! Will put N/A for now. Just to say this is the case with few cases currently in the system, such as: https://center.alces-flight.com/clusters/1/cases/RT11929

**Comment by jamesremuscat** [comment]
Ah, yes, a bunch of the legacy stuff (anything starting `RT`) won't have comments because it happened before we added comments :slightly_smiling_face:

**Comment by DavidMarchant** [comment]
Ah right, thanks for the info!
