### ISSUE TITLE
UX: allow multiple case values to be updated at once

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#396]
Old habits die hard, and in RT this was a one-click operation.  I've frequently found myself losing the comment I've just typed, or the amount of time worked, depending on where my brain has decided to click. :)

I think we should replace all the buttons on this page (including assignee change) with a single "Update case" button (obvs. don't add an empty comment if none is supplied :smile:).  Possibly also turn "enable/disable commenting by site contacts" button into a checkbox/toggle.

Think this also relates to #72 and could be wrapped up with the work on that feature (some of which I think is also currently being covered by the work on component/service associations -- we should revisit #72 to determine what other things are still needed).

The site contact experience should probably remain unchanged as, IIRC, they only have "add comment" anyway.

**Comment by bobwhitelock** [comment]
> I've frequently found myself losing the comment I've just typed, or the amount of time worked, depending on where my brain has decided to click. :)

FWIW, and not that this resolves the underlying issue of whether the case page UX can be improved, but you could fix this for Flight Center (and every other site) at the browser level with a plugin, e.g. [this one](https://chrome.google.com/webstore/detail/typio-form-recovery/djkbihbnjhkjahbhjaadbepppbpoedaa?hl=enhttps://chrome.google.com/webstore/detail/typio-form-recovery/djkbihbnjhkjahbhjaadbepppbpoedaa).

> The site contact experience should probably remain unchanged as, IIRC, they only have "add comment" anyway.

They can also escalate level 1/2 cases to level 3 (and I think take actions on change requests when these are available) IIRC.

**Comment by mjtko** [comment]
> FWIW, and not that this resolves the underlying issue of whether the case page UX can be improved, but you could fix this for Flight Center (and every other site) at the browser level with a plugin, e.g. this one.

Ooh, nice, thanks for the pointer.  I think you're right that it doesn't resolve the underlying UX issue tho. :)

> They can also escalate level 1/2 cases to level 3 (and I think take actions on change requests when these are available) IIRC.

Yup, tho they can't comment until escalated anyway. :)  Not sure about how CR changes affect things, not seen those yet.

**Comment by mjtko** [comment]
Can we get this added, or at least get the browser to remember the contents of the comment field in case I click the wrong thing please. 😢

**Comment by jamesremuscat** [comment]
Implemented in #762.
