### ISSUE TITLE
Change default cluster charging information text

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#399]
* Use "minutes" rather than "m", "hours" rather than "h"
 * Specify times are business hours not elapsed hours

**Comment by jamesremuscat** [comment]
We don't ever use time in association with credit charges. I'm assuming you mean the entries for "time worked changed" in the case history feed.

These are only shown to admins. Is this still a release blocker?

**Comment by mjtko** [comment]
As discussed IRL, think this is a database thing. I'll take a look.

**Comment by jamesremuscat** [comment]
`charging_info` column in the `clusters` table (or `Cluster#charging_info) is where this lives. :)

**Comment by bobwhitelock** [comment]
The default charging info is set inline as we just wanted a quick addition of this before some recent release, so may require code changes if we want to change this as well:

https://github.com/alces-software/alces-flight-center/blob/aa9e307083c15df337a693207e9948b00cdf2765/app/javascript/View/Charging.elm#L72-L91

**Comment by mjtko** [comment]
Thanks @bobwhitelock - I'll override it at the cluster level for now so we don't need to make any code changes, but let's leave this open to remind us to make the code change in a future release.

I'll attach the updated text once I've written it.
