### ISSUE TITLE
Implement 'Engineering Level' Support

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#412]
I'd like to be able to add an 'engineer level' for each case logged. 

- levels 1-3
- Only admins can assign a level
- Each admin has a max engineering level stored with their user account
- Tier 1-2 tickets are automatically given level 1 at creation
- Tier 3 tickets are automatically given level 2 at creation
- (UI suggestion) Modify the 'assign to' interface to list names in order of their max level (ideally with a indication of their level)- if name is chosen of a higher level engineer the case level is raised to that level at the same time as it being re-assigned

**Comment by jamesremuscat** [comment]
Mark says "don't do any validation between case and engineer levels yet".
