### ISSUE TITLE
Automatic assigning of cases per site

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#413]
I'd like to have dedicated first line engineers for cases created per site. 

- Against a site store admin name of person initially responsible for tier1,2 and 3 tickets
- When a case is logged by that site - automatically assign the correct admin 

Don't think we really need a custom interface for this it'd be changed very rarely - happy with it to be done in the database directly unless someone thinks otherwise

**Comment by jamesremuscat** [comment]
- No email to be sent
- Case history feed entry to be made
