### ISSUE TITLE
UX: once a case is resolved no longer highlight it in the "my cases" section

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#416]
Once a case is resolved, it no longer needs to be displayed in the "my cases" section of the resolved cases view.  i.e. that view doesn't need to distinguish by grouping cases assigned to the current user at all.

**Comment by jamesremuscat** [comment]
The "resolved cases" view is now "the cases view with some filters applied"; I've resolved this issue by only highlighting open cases in the "my cases" section (regardless of filters). I think the net result is the same.
