### ISSUE TITLE
Maintenance period extensions

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#42]
We need to extend the maintenance functionality with date ranges, so that we can book something out for maintenance (and apply for authorisation from the customer) between a start time and end time, rather than immediately.

**Comment by bobwhitelock** [comment]
@ste78 I have some questions on how you think this should work. Currently the way maintenance windows work is:

- an admin requests maintenance for a particular component/service/cluster and in association with a particular case;

- a user confirms this;

- the admin later ends the maintenance.

At each step of this process a comment is left on the corresponding ticket indicating what happened and any action needed by the user. The component/service/cluster is also considered to be 'under maintenance' for the period between confirmation by the user and maintenance being ended by the admin.

In the new system:

1. Should the requested start and end times always be required to be set by the admin when requesting maintenance? Or can these optionally be unset, in which case the previous behaviour will presumably remain?

2. If these can be unset, should this be possible independently? So maintenance could have a requested start time but will end whenever this is triggered by the admin (or vice versa)?

3. If maintenance windows do have start and/or end times set, should this automatically indicate the item is under maintenance/maintenance has ended, and make a comment on the original ticket indicating this?

4. For the initial version of this feature, do we need to support users altering the requested maintenance start and end times?

**Comment by ste78** [comment]
1. All maintenance requests should have a start / end time. The current ones without times are not really that useful. 
2. can’t be unset
3. yes if been approved, if it’s not approved before the start date then the maintenance requests becomes expired a comment sent out at the start time saying that ‘the maintenance request was not authorised by the user in time’
4. Nope, editing not required. but we can cancel one and make another with different dates though?

**Comment by bobwhitelock** [comment]
Thanks for the previous answers @ste78 - one new thing which has now come up: with the change to maintenance being for scheduled times, is there still a need for the quick maintenance request buttons for cases (the spanner shown alongside cases which immediately requests maintenance for the associated cluster/component/service)?

Now that all maintenance needs a requested start and end these will no longer be able to immediately request the maintenance, and would need to just become links to start requesting maintenance with the given cluster/component/service and case already selected, so I'm not sure how useful they would be over just creating maintenance in the more general way.

**Comment by ste78** [comment]
yep agreed, for other coming functionality l’m also thinking maybe we drop that feature. can we discuss on monday IRL?

**Comment by bobwhitelock** [comment]
This has now been done as originally requested with the merging of the above two PRs. Some additional related changes have been requested before this can be deployed, the main one of which is being tracked at https://trello.com/c/k81APmbi/191-expired-maintenance-should-still-show-in-table-users-can-always-change-requested-start-and-end-date-when-confirming.
