### ISSUE TITLE
Consider: create new case referring to existing resolved/closed case

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#420]
Currently, by design, once a case has been resolved/closed it is no longer possible for a customer to comment on the case.  However, there is a flow that goes:

1. We believe the case is resolved, so resolve/close the case.
2. Customer discovers they have a query related to the resolved case but are't able to and must open a new case to do so.

While this request may be fixed/made obsolete by #208, it might also complement it -- once a case has been manually or automatically accepted, there is still a possibility that new/related information may come to light.

I'd suggest a "create related case" button, which generates a new case (use the same details as existing case?), with a reference to the existing case and allows the customer to add a comment containing the new information.

Cases open this way should immediately be considered tier 3.

**Comment by jamesremuscat** [comment]
Spec was further developed to:

> When a case is verified or closed, it is not possible to reopen it. However, we want to make it possible for a subsequent case to be opened with the same characteristics as the first.
> 
> Opening a related case should create a new case:
> 
> - With the same issue, subject, and associations as the first
> - As a tier 3 case
> - With “details” specified by the user (e.g. create a mini “new case” form with just a field for details)
> - Retaining a reference to the original case

If the case's cluster has the `show_charging_info` flag set then we should show the usual credit allocation message on the mini-form.

**Comment by jamesremuscat** [comment]
Implemented in https://github.com/alces-software/alces-flight-center/pull/729.
