### ISSUE TITLE
Reduce size of headings in rendered markdown

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#422]
The headings (`h1` and `h2`) in the rendered markdown appear larger than much of the rest of the page content.  We should drop the size of the headings to say, `1.75rem` and `1.25rem` for these (and possibly update the size of `h3` through `h6` too).

**Comment by mjtko** [comment]
I think the heading sizes also need to apply in places other than the change request page (headings can be used/abused in other places Markdown is accepted).

**Comment by jamesremuscat** [comment]
Ah, good catch. My brain had too tightly coupled this to #423!
