### ISSUE TITLE
Ordering of sites on sites dashboard

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#435]
On the sites dashboard, the ordering of the sites appears arbitrary (presumably whatever order the database/app has decided at some start/restart or other).

Enhancement request is:

1. Introduce a field called something like "site identifier" or "site nick name"
2. Order by this field (alphanumerically descending)
3. Display this field in advance of the official site name on the dashboard (ideally in different style or colour to differentiate)

Reasoning for (1) is so we can both use familiar terms to refer to the site as well as not needing to worry about pronouns or common inversions like "University of X" rather than "X University" etc.

**Comment by mjtko** [comment]
For existing sites, the new field can default to the same as the existing name field.

**Comment by DavidMarchant** [comment]
hey @mjkto can I just confirm what is wanted with this. So a separate entry on the 'All Sites' table that displays a new attribute to be stored about all sites, their `site identifier`? and for all current sites i should set this to the existing name

**Comment by DavidMarchant** [comment]
just realised that that @ didn't work as i copied it in - @mjtko

**Comment by mjtko** [comment]
Yup - spot on!

**Comment by DavidMarchant** [comment]
Ah great, thanks :)

**Comment by DavidMarchant** [comment]
![image](https://user-images.githubusercontent.com/24327288/45091155-82147180-b109-11e8-8409-ebc071ea69dd.png)
@mjtko is bold-ing the first field good by you? Or something else?

**Comment by mjtko** [comment]
Well, if you're going to give me an opportunity to put forward my opinion!...

Table would be nicer IMO. :)

**Comment by DavidMarchant** [comment]
Ah fair do's! I'll give it a shot

**Comment by DavidMarchant** [comment]
![image](https://user-images.githubusercontent.com/24327288/45097423-c4927a00-b11a-11e8-937d-559214518ea0.png)
How's this @mjtko ?
(I first did it without headings but thought it looked a little strange)
![image](https://user-images.githubusercontent.com/24327288/45097551-058a8e80-b11b-11e8-884e-f4f829f7b52e.png)

**Comment by mjtko** [comment]
Yup, nice -- it's now not sorted how I expected tho!

**Comment by DavidMarchant** [comment]
Oops haha, sorted now
