### ISSUE TITLE
Unable to create new users through admin dashboard

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#436]
Trying to create a new user is prevented by "password cannot be blank" error, but there is no password input box (presumably cos we use SSO now).

**Comment by jamesremuscat** [comment]
Workaround: users can be created through the Rails console:

```ruby
User.create(name: 'User Name', email: 'user@example.com', site: <site>, password: 'string-is-ignored', role: 'viewer')
```

`role` can be `primary_contact`, `secondary_contact` (both one per `Site`) or `viewer`.

Proper fix is to override `password_optional?` in `User`.

**Comment by mjtko** [comment]
There can be multiple `secondary_contact` per site, no?

**Comment by jamesremuscat** [comment]
Yes, I need tea this morning. Sorry :worried:
