### ISSUE TITLE
Deleting a Component should delete its ComponentExpansions

### ISSUE THREAD

**Issue by jamesremuscat** [alces-software/alces-flight-center#437]
https://sentry.io/alces-software-ltd/alces-flight-center/issues/613171857

This elides the wider question of whether allowing deletions is a good thing or not as they might be referred to from elsewhere; in this case probably a `dependent: :destroy` is what we need since deleting erroneous things as part of the setup process (before they can have complicated relationships with Cases and MWs and stuff) should be possible.

**Comment by mjtko** [comment]
I think this has been made obsolete with the implementation of #545 - @jamesremuscat please reopen if I've misunderstood!
