### ISSUE TITLE
Ordering of cases in case view.

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/alces-flight-center#439]
Could the ordering of tickets in the case view possibly be switched so that cases owned by yourself are not automatically placed at the top of the table? The highlighting of the cases you own is fantastic and shows which cases you are handling - but the ordering of them by date is more important when it comes to viewing all of the cases for a site/cluster/all tickets, since the cases are time sensitive. @jamesremuscat mentioned that we'll be able to filter cases by owner in a future release anyway, so being able to view just the tickets owned by yourself is possible.

**Comment by jamesremuscat** [comment]
Fixed in #542.
