### ISSUE TITLE
Cosmetic: buttons seem to animate into existence when rendered

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#449]
I've noticed that the buttons rendered in the brand bar ("sign in") and the nav bar ("all sites", site name, cluster name etc.) have an odd "vertically expand from middle animation" on page transition.

This doesn't appear to be the case on the current live system -- perhaps an odd animation style has leaked out to places it should not during the last iteration?

**Comment by jamesremuscat** [comment]
I don't think this is an animation, rather a delay before some styles are applied. Worth investigating.
