### ISSUE TITLE
Allow a proposed change request to be sent back to draft

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#486]
Use case: customer spots issue with CR and requests changes.  At the moment this isn't possible without opening an entirely new case.

To make it possible, we should allow the following process:

1. Customer declines change request and makes request for changes
2. Once declined, admin has ability to place change request back into draft
3. Admin can make edits as usual for draft CRs
4. Admin proposes modified/updated change request

**Comment by mjtko** [comment]
Or... even better:

1. Customer hits a "request changes" button
2. Admin makes edits and proposes updated CR again
3. Customer accepts CR

**Comment by jamesremuscat** [comment]
I like the second option better, and it should be straightforward: just need to add a new transition `:request_changes` from `proposed` back to `draft`, give contacts permission to do so, and add the button to the UI. Details of the changes required can be handled via case comments.

**Comment by atoghill** [comment]
This feature has now been merged in `develop`, closing this issue
