### ISSUE TITLE
Cluster documents should automatically be made public with pre-signed URL

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/alces-flight-center#488]
All Cluster documents, regardless of whether they're public in S3, should be made available to Cluster users using a time-limited, pre-signed URL. The code to do this exists: https://github.com/alces-software/alces-flight-center/blob/185b9bf2db3eda31b7551ce22e605fe897706054/app/models/cluster/documents_retriever.rb#L47-L52 but for some reason this didn't work when done in production - see from https://alces.slack.com/archives/C72GT476Y/p1533727235000132.

I believe this is the first time we've used this feature in production so it's possible it's never worked here, and also possible this is a server configuration rather than a code issue.

**Comment by jamesremuscat** [comment]
This was an issue with the IAM policy defined for Flight Center.

We needed to specify both a bucket and object resource ARN for the permissions we were granting - previously FC had lacked `Get` permissions on objects within its bucket, and just had them for the bucket itself.

Both staging and production use the same IAM credentials so this fix covers both.

FTR:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:Get*",
            "Resource": [
                "arn:aws:s3:::alces-flight-center",
                "arn:aws:s3:::alces-flight-center/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:List*",
            "Resource": [
                "arn:aws:s3:::alces-flight-center",
                "arn:aws:s3:::alces-flight-center/*"
            ]
        }
    ]
}
```
