### ISSUE TITLE
Document upload

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#492]
Opening as a placeholder to discuss what we could do in terms of a document upload feature rather than need to upload the wonderfully capable and unlikely to break s3 interface. Basically what sort of timescales would we be looking at to implement something basic that allows me to upload pdf scribbles i've made onsite directly to FC documents page.

**Comment by jamesremuscat** [comment]
This sounds quite similar to existing functionality we have elsewhere - assuming I can do some copy/paste, a basic implementation will probably be ~2 days of effort to implement.

OOI: How large are your PDF scribble files?

**Comment by mjtko** [comment]
PDF scribble files determined to be ~1MiB/page of scribble.  I think it depends how intensive the scribbling is. Anyway, it's "megabytes" not "gigabytes". :)

**Comment by jamesremuscat** [comment]
I'll assume unless told otherwise that only admins should have permission to upload to S3 in this manner.
