### ISSUE TITLE
Hide checks tab when no checks are defined

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#501]
While we're hiding the checks section on the cluster dashboard page when no checks are defined for the cluster, the checks tab is still visible.  Can we hide this too please?

**Comment by atoghill** [comment]
Woops I should have thought about this when I hid the widget in #498. This should be a simple change though 👍

**Comment by jamesremuscat** [comment]
Fixed by #510 (release branch) / #502 (develop).
