### ISSUE TITLE
Change request workflow enhancements (was: Allow admin to reopen change request after cancellation)

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#504]
Another workflow enhancement -- if a change request is cancelled, then it turns out a CR is actually needed, we're currently stuck in the terminal "cancelled" state.

Can we add a "reopen" button (for admins only) to put the CR back into draft?

**Comment by jamesremuscat** [comment]
The agreed process for this was raising a new case.

If that is insufficient, please reopen this issue :slightly_smiling_face:

**Comment by mjtko** [comment]
Yup, insufficient (cos it's time consuming to open a new case), but not urgent, so will reopen this issue and we can look into adding it in a future release.

**Comment by mjtko** [comment]
Also: retract change request (i.e. pull it out of requesting authorisation and back to draft).  See https://alces.slack.com/archives/C72GT476Y/p1534326642000100

**Comment by mjtko** [comment]
Also: admin needs access to buttons currently only shown to site contacts so we can progress CRs from our end.

**Comment by atoghill** [comment]
#506 is related to this and should be done at the same time (Talking to myself, totally normal)
