### ISSUE TITLE
Fix date formatting in credit charge table

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#508]
While #391 has been achieved, the side effect has been to modify the rendering to a slightly less friendly "2018-08-08" format, rather than the previous "8th August 2018".  This may or may not be intentional, but can we restore the friendly rendering of this date please? That may break the coincidental fix of #393, but possibly that's been fixed elsewhere now.

Also, the hover text no longer includes the time.  I'm happy for this to continue to include the day of week and time of day, cos it's only available on hover and might be handy.

**Comment by mjtko** [comment]
Ok, it's fine to be a date.  We have the date/time of resolution of a case anyway, which is what I thought this information was, and what we might need to display elsewhere in future.

The change made in ba5844a is sufficient to fix this issue.

**Comment by jamesremuscat** [comment]
Fixed in #511 (develop) / #512 (release).
