### ISSUE TITLE
Consider: Don't automatically fill subject field for new cases

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#515]
The subject field is automatically prepopulated with the title of the issue.  Whilst this is handy for time-pressed customers, it has lead to a proliferation of similarly titled cases.

We should consider some/one/none of the following:

1. Not automatically filling this in forcing the user to type in a meaningful subject
2. Better automatic generation of the case subject based on the fields available for the particular issue

(1) seems easier than (2), though (2) seems friendlier than (1).  For discussion. 😄

**Comment by jamesremuscat** [comment]
Steve says "No".
