### ISSUE TITLE
Render cluster check example commands with markdown

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#517]
Some of the cluster check "example commands" are URLs and should be rendered as clickable links rather than as `<code>`-style blocks.

To address this, perhaps the easiest fix is to make the "example commands" markdown-aware, and introduce ` characters for the `<code>`-style ones and `[target](url)` for URL-style ones.  I'm open to other suggestions tho. :)

**Comment by jamesremuscat** [comment]
@mjtko did this in #823.
