### ISSUE TITLE
Add change request tracking (Tier4)

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#52]
Track change requests through FlightCenter

More to come on how this should work..

**Comment by ste78** [comment]
change requests are similar to cases in that they ultimately should create rt tickets, but based on a different template and not involving users in the rt emails

we need a form for an admin to start a new change request against a cluster fields:
date/time created
change request id: <cluster name in caps><highest change request id for this cluster + 1> - we guess but also editable 
project title 
project overview
number of credits used

status, choose one from : PLANNING, AWAITING AUTHORISATION, IMPLEMENTING, HANDOVER, COMPLETE

when the CR is marked as complete, number of credits is deducted from the site total

**Comment by ste78** [comment]
rt should be updated on each change but customer site contact emails should not be included in rt, we use it for internal tracking only

users should be able to view all cr’s on their account, but for now not do much with them.

**Comment by bobwhitelock** [comment]
From meeting:

- Will need to send email from Flight Center for change request confirmation (customers shouldn't be aware things are logged in RT for internal tracking behind the scenes).

- Customers will keep filling in change request form (for now), later we will fully implement this in Flight Center.

- 'change request id' starts from 1, increments on a per-cluster basis.

- See https://docs.google.com/spreadsheets/d/1rVQL7sYR6AcPnCglSMT8JX5c6zq2GAh8rIOQY8M67tc for existing tracking table.

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/JxI8jNe3/145-add-change-request-tracking

**Comment by ste78** [comment]
This is superseded somewhat by the new concept of tier 4 cases.  I’ll just update the subject of this issue though because the concept remains primarily the same. 

- only admins would be blue to promote a tier 3 case logged by a user to a tier 4
- tier 4 case is essentially a tier 3 case that has a ‘Change request form attached’
- here is the current paper cr form, but a lot of that is overkill and we’d only need to implement the major concepts in flight center
https://docs.google.com/spreadsheets/d/1D7NP_UpPQhN3tlossc0W6a2veNIOm0ezt8Ks9FQBLds/edit?usp=sharing

- we’d have some way for the user to authorise the cr form and move it through the workflow described above

**Comment by jamesremuscat** [comment]
Some thoughts on implementing this:

- A `Case` has zero or one `ChangeRequest`s attached
  - Corollary: a CR may, through its `Case`, be associated with an entire cluster, or a component or service of that cluster
- A `Case` is tier 4 iff if has a `ChangeRequest`
- Only a tier 3 case may become a tier 4 case
  - Corollary: no case can be created as a tier 4
- There is no change in `Case` state on escalation to tier 4 e.g. it stays `open`
- Change requests are uniquely identified by their corresponding case ID e.g. `BAR42`
- On triggering an escalation to tier 4, admins are presented with a form to enter CR information
  - Observation: At some point we changed from "customers fill out this form" to "Alces fill out this form"
  - Can "Project title" be taken from the `Case` subject or should this be separate?
  - Can we collapse "Project overview", "proposed changes", and other long-form text sections into a single `details` textarea?
    - This is another place where Markdown editing/rendering would be useful
  - Single numeric field for "credits used" - no ongoing per-period costs managed through this system
  - Are we expecting admins to be able to enter all necessary information in one session? Might it be worth having a "draft" state whereby admins can edit these fields over multiple sessions, then promote to "awaiting authorisation" when ready? Suspect it will be easier to address this now than later.
- On completion of CR form, email is generated and sent to site recipients, event appears in case events feed with link to review CR
- When happy, customer can approve or decline CR
  - Approval moves CR into "in progress" state
  - Declining moves CR into "declined" **and resolves original `Case`?**
  - Both generate emails/events
- Once change has been effected, admin can move CR into "HANDOVER" state (event, email)
- If a customer is not happy to resolve, the CR stays in HANDOVER (it doesn't get reverted to "in progress"
- Once customer is happy, customer can move CR into "COMPLETE" state, resolving original `Case`
- When closing the case, the minimum credit charge to be added is the value of the CR; additional credits may be charged on top of this amount. Only the total credit charge is stored and displayed (e.g. just a single number per `Case`, as now)

**Comment by ste78** [comment]
_Can "Project title" be taken from the Case subject or should this be separate?_  **yep**
_Can we collapse "Project overview", "proposed changes", and other long-form text sections into a single details textarea?_ **yes, if we have markdown so we can create our own headings in this section**
_Are we expecting admins to be able to enter all necessary information in one session? Might it be worth having a "draft" state whereby admins can edit these fields over multiple sessions, then promote to "awaiting authorisation" when ready? Suspect it will be easier to address this now than later._ **Yep thats worth doing**
_Declining moves CR into "declined" and resolves original Case?_ **I'm not convinced about resolving the case automatically, I can see why you suggest that, theres not much place a case can go once the CR is declined but I think I'm happy with admins still resolve the case manually for now ** 

Everything else I agree with, looks excellent 👍

**Comment by jamesremuscat** [comment]
> Can "Project title" be taken from the Case subject or should this be separate? 
> > yep

Just for clarity: which? ;-)

**Comment by ste78** [comment]
I don't think its a thing, as its a 1:1 correlation I think the CR just adopts the same name/subject of the case to which its associated

**Comment by bobwhitelock** [comment]
Just thought of something related to this, not sure if this is likely to be an issue: we already have a system of change requests in place for Clusters managed through both Flight Center and RT, where a change request ID is in the format Cluster short code + unique index, e.g. `BAR123`. This is the same format we now use for Flight Center Cases and plan to use for associated change requests:

> Change requests are uniquely identified by their corresponding case ID e.g. BAR42

This means that, for Clusters already managed by Flight Center:

1. It is possible that they already have old-style change requests with IDs in this format, which means either a change request exists with an ID, say `BAR42`, which implies it is associated with Flight Center case `BAR42`, even though it is unrelated - note that this has already happened, see https://center.alces-flight.com/cases/RT11820.

2. Similarly to (1), it is possible that new-style change requests will be created when this is possible with the same ID as existing change requests, meaning we could have two unrelated `BAR42` change requests, one in Flight Center and one outside.

I'd imagine the same will also occur in future as we move existing Clusters managed via RT to use Flight Center, except it's likely to occur more often as these Clusters will have more existing change requests, and may have more old-style change requests created until the point we switch them over.

**Comment by ste78** [comment]
yep, acknowledged. We'll deal with any confusion outside of flight-center when that happens, you guys don't need to worry about it :)
