### ISSUE TITLE
Adjust 'time to first response' to use eight-hour days?

### ISSUE THREAD

**Issue by jamesremuscat** [alces-software/alces-flight-center#523]
In https://github.com/alces-software/alces-flight-center/issues/479#issuecomment-412929305 @mjtko said that:

> "days" should also take [business hours] into account. i.e. once a response has exceeded 8h, that's 1d.

Should this also apply to the "time to first response" now given on the credit usage pages for a cluster?

**Comment by mjtko** [comment]
I'm happy with leaving that as hours for the time being.
