### ISSUE TITLE
Administrative ("internal") cases

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#526]
Allow an admin to open a case primarily for internal use/tracking.

Additional "tier" tab available for admins only, titled "Administrative".

This puts the case into a slightly different mode where:

1. There is no site contact interaction.  No emails are dispatched to site contacts for administrative cases (i.e. skip the usual mails to site contacts for creation, subject update, comments).  Ref #525, no site contact is assigned.
2. Case is still visible to site contacts, but cannot be interacted with by them. (Possible future: site contact could escalate to tier 3, to be able to comment, but not for now.)
3. No request maintenance button.
4. Admin can escalate to tier 2, which would then convert the ticket into "normal mode" (allowing for maintenance requests, further escalation, opening comments to site contacts, usual notifications for site contacts).

**Comment by jamesremuscat** [comment]
Just a clarification: I'm assuming that by point 2. above you weren't meaning that administrative cases should be invisible to viewers, but that they should be "still visible to site contacts _and viewers_"?

**Comment by mjtko** [comment]
> should be "still visible to site contacts and viewers"?

Yes please.

**Comment by jamesremuscat** [comment]
Implemented by #557 and #571.
