### ISSUE TITLE
Can't create cases that are linked to components

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#563]
Currently can't create a case for "Hardware Management" -> "Suspected hardware issue":

<img width="1389" alt="screen shot 2018-09-03 at 18 31 48" src="https://user-images.githubusercontent.com/206834/44997632-b5d78600-afa7-11e8-8e93-88afa48e997d.png">

**Comment by jamesremuscat** [comment]
There's some rogue validation on `Component` that's failing when `info` is the empty string (because Rails insists that null and empty string are both "absent" values) .
