### ISSUE TITLE
Allow admin to escalate/change tier of case without generating a notification

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#576]
Additional means to move a case between tiers for admins only.

No emails sent to site contacts, but support team notifications to be generated as usual.

Should generate a card on the case history, tho should state for e.g. "Set this case to tier 3 (General Support)." rather than "Escalated this case to tier 3 (General Support).".

**Comment by jamesremuscat** [comment]
Note to future self: this includes escalating *and de-escalating* cases across tiers 2-4 e.g. admins should be able to reduce a tier-3 case to tier-2.

**Comment by jamesremuscat** [comment]
Does it make sense to be able to de-escalate a case from tier 4 (change request) down? Or escalate a tier 2 or 3 case to tier 4 _without_ a change request?

**Comment by atoghill** [comment]
@mjtko When you get a chance it would be great to get your thoughts on the above comment

**Comment by jamesremuscat** [comment]
Also relevant to this thread:

https://github.com/alces-software/alces-flight-center/issues/577#issuecomment-420586345

> I think retaining the existing wording is fine. "Escalate" on way up the tiers, "Set" (for admins only) if set to a lower tier.

**Comment by mjtko** [comment]
De-escalate (i.e. "set" downwards) from tier 4 is fine if the change request has been cancelled.  Can't set to a lower tier if a change request is open or complete.

Escalation from tier 2/3 to tier 4 without a change request doesn't make sense.

(Aside: my initial comments about emails being sent to site contacts is moot, cos we don't send emails to site contacts when changing tiers at the moment.)

As per comments on #577, use the word "set" when tiers are being reduced, otherwise let's stick with "escalate".

**Comment by atoghill** [comment]
@mjtko Do you want the ability to transition a T2/T3 case to a T4 using these new controls? Or do you want that process to only work via the current method?

**Comment by mjtko** [comment]
I think the only question is about going directly from "T2" -> "T4", but I can't see a use case for that -- we'd  escalate to T3 and then open a change request to get it to T4 as it is at the moment.

**Comment by atoghill** [comment]
Cool thanks for the clarifications. For now I'll keep these controls as is, allowing admins to freely change between T2 and T3.
