### ISSUE TITLE
Change "Escalate" button

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#577]
Change wording on "Escalate" button to say "Open for comments".

At the same time, remove warning about it becoming chargeable, simply escalate it.

**Comment by jamesremuscat** [comment]
Do we want to change the wording of the case history card when this happens? At the moment it will say "Escalated this case to tier 3 (General Support)".

We could have it say "Set this case to..." (cf. #576) or "Opened this case for comments" (with only the admin "sneaky" usage using the 'Set' wording). (Or something else!)

**Comment by jamesremuscat** [comment]
@mjtko Any thoughts on the above?

**Comment by mjtko** [comment]
I think retaining the existing wording is fine.  "Escalate" on way up the tiers, "Set" (for admins only) if set to a lower tier.
