### ISSUE TITLE
Order component groups in "All component" list alphanumerically

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#588]
Currently the ordering looks non-deterministic.  Should be ordered alphanumerically.

This applies both to the groups when displayed on the page as well as in the dropdown menu.

**Comment by mjtko** [comment]
Also sort in the picker widget for assigning components/services to a case please.

**Comment by mjtko** [comment]
I won't open another ticket regarding the picker widget, but the components aren't sorted in this atm either:

<img width="532" alt="screen shot 2018-09-06 at 10 07 38" src="https://user-images.githubusercontent.com/206834/45147389-b5fc9f00-b1bc-11e8-9bcb-cf9086c93472.png">

**Comment by DavidMarchant** [comment]
Hey @mjtko, in the site picker would you also want the top level (i.e. components THEN services) &/or the services themselves being sorted for this? Or should I just do the components + component groups?

**Comment by mjtko** [comment]
Keep services first please.  Sorting the service names seems sensible tho, yup!

**Comment by DavidMarchant** [comment]
Cool, cheers
