### ISSUE TITLE
If an admin created a case, they should be the initially assigned engineer

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#591]
If an admin creates a case, they're not able to comment on it without then going through the step of assigning it to themselves.  In the situation where there is no default engineer assignment for a site, can we set the assigned engineer to the creator please.

**Comment by atoghill** [comment]
@mjtko Were you only wanting the admin to be assigned if there is **no** default engineer set for that site? Or should the admin always be assigned as the engineer for that case if they created it?
