### ISSUE TITLE
If primary contact is made viewer existing cases they are assigned to are not assigned to anybody

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#595]
It's a bit of an edge case, but what we should do in this situation is ambiguous (and wasn't specified).

As the move from primary contact -> viewer involves temporarily having no primary contact, I think the best we can do here is make the assumption that a secondary contact should be assigned.  So let's go for that -- if there's no current primary contact, assign cases currently assigned to the former primary contacts to the first secondary contact.

If that's not what we want IRL in a situation, then we'll have to be careful to do:

1. U(primary) -> U(secondary)
2. V(viewer/secondary) -> V(primary)
3. U(secondary) -> U(viewer)

But I think this is better than having unassigned cases.

**Comment by jamesremuscat** [comment]
The situation is a bit worse than described: when the primary contact is being changed to be a viewer, then before that change is saved to the database we call the `reassign_cases_if_necessary` method, which detects that the user is being changed to be a viewer. It then iterates over the cases assigned to that user and reassigns them to the site's primary contact - which at this point is still the user in question.

The end result is that we leave the cases assigned to the former primary contact (leaving their record invalid in the database) and no reassignment happens.

Therefore I think the specification above should be "If there's no current primary contact, or the user in question is currently the primary contact, assign cases to the first secondary contact".

**Comment by jamesremuscat** [comment]
@mjtko Can I take this opportunity to confirm that we don't want to send emails out for this bulk reassignment? It could get very spammy...

**Comment by mjtko** [comment]
Yes, correct, no notifications for this bulk reassignment stuff please.  We may want to consider a single (admin only) notification for when this is performed later on, but right now, silence is fine. :)
