### ISSUE TITLE
Also include "Nobody" cases on Global view

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#604]
While it should be uncommon for cases to have no engineer assigned (i.e. "Nobody") now we've got default engineers for a site, if such cases exist, it would be handy to have them shown in the Global view for admins.

Suggested position is at the top, above your owned tickets.

**Comment by mjtko** [comment]
Not sure it's necessary to show these at the top.  It might be nice to highlight them with a different colour (admin only) to make them stand out in all lists.  Perhaps orange/yellow/red to indicate warning.

**Comment by atoghill** [comment]
Just for clarification are you referring to the `My Cases` view of the Global dashboard? There are other areas  of Global that show such cases by default already.

**Comment by mjtko** [comment]
I was, but I'm not sure this is actually useful.  I think highlighting them in some way would probably be more useful as anybody can then see at a glance cases that aren't assigned to anybody on the "Active cases" view.

**Comment by jamesremuscat** [comment]
Just to clarify the clarification (!) @mjtko - are you saying that this issue is now obsolete and you've changed your mind, and that #710 fully covers the requirements here?

**Comment by mjtko** [comment]
Yes, this is covered by #858 as it stands, I don't see the value in displaying cases owned by nobody on the "my cases" dashboard, as it should be possible to see those at a glance on the "active cases" dashboard at a glance now they're highlighted.
