### ISSUE TITLE
Navigation overhaul

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#608]
Placeholder issue for considering ways in which the navigation could be improved by making better use of  the product bar and perhaps removing/changing the way the current tabs system works.

**Comment by jamesremuscat** [comment]
Some WIP ideas:

![cases - demo cluster - alces flight center - google chrome_032](https://user-images.githubusercontent.com/3471844/47449531-c68fc580-d7ba-11e8-8c42-555435e349f9.png)

**Comment by bobwhitelock** [comment]
It's a work of art @jamesremuscat! :heart: :art:
