### ISSUE TITLE
Wording change to "resolved" email

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#618]
Small thing, but perhaps a bit confusing.  The "resolved" email currently says:

> DEMO1 has been resolved by Chris Demo and is awaiting closure
> 
> To comment, or to see more details of this case, please visit the following link:

But user's can't comment any more (cos the case is resolved).  Change this to:

> To see details of this case, please visit the following link:

As this only affects engineer-only email notifications, this is low priority. 😄

**Comment by jamesremuscat** [comment]
This email becomes customer-facing as part of the case workflow changes in 2018.8, so I'm adding this to that milestone. (Having already committed a fix...)
