### ISSUE TITLE
Presence of engineering-level notes breaks documents page for contacts

### ISSUE THREAD

**Issue by jamesremuscat** [alces-software/alces-flight-center#630]
#629 has uncovered a critical bug in how we handle `engineering`-visibility cluster notes.

If a cluster has one or more notes with `engineering` visibility then customers are unable to view the documents tab. This is because we check read permissions of records `after_find`, and customers don't have read permissions on `engineering`-visibility notes, so when we start iterating through `cluster.notes` an exception gets raised that we then turn into a 404.

We need to filter the set of notes to iterate on in the controller. We also need better test coverage in this area.

Unless anyone disagrees, this is demanding of a point release for `2018.7`.

**Comment by mjtko** [comment]
Yes, hotfix please. :)
