### ISSUE TITLE
Show charging message when reopening a case

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#684]
https://github.com/alces-software/alces-flight-center/issues/208#issuecomment-397007028 ...
> tier0-2 cases automatically become a tier 3 case when re-opened, the usual ticket escalation warning about charges should be given.

We're not showing this charging warning at the moment, regardless of the setting of the "show charging info" flag for the cluster.  I think we want to show this message if "show charging info" is enabled.

**Comment by jamesremuscat** [comment]
Do we want to show it even if the case is already tier 3 (or higher)? In such a scenario the "potential use of available account credit" has already been authorised.

**Comment by mjtko** [comment]
Makes sense not to in that scenario, yup.
