### ISSUE TITLE
Tier 1/2 cases always get engineering level 2

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#685]
This is because of the application of the rule:

> if name is chosen of a higher level engineer the case level is raised to that level at the same time as it being re-assigned

And as all engineers are at level 2 by default, this is causing tier 1 & 2 cases to immediately be set to engineering level 2 on assignment (or creation, as all sites have a default engineer set).

Proposal of a solution/change in behavior to follow... :)

**Comment by mjtko** [comment]
Ok, not sure what the solution is here.  Two options for now:

1. Remove/disable the "raise level" logic until we decide how this should work, so tier 1/2 cases get the expected engineering level.
2. Do nothing.

**Comment by jamesremuscat** [comment]
Agreed with @ste78 and @mjtko to take option 1 i.e. disable the logic linking engineer EL to case EL.
