### ISSUE TITLE
Should directory console service be working? (demo/staging)

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#688]
Not sure where the problem lies here, or whether I'm misremembering that this should be configured, but I can't access the directory console for the demo site on staging, so logging an issue here for us to investigate it.

**Comment by benarmston** [comment]
The staging version of terminal services client and server were running an old version of the code that wasn't compatible with the staging version of FC.  I've deployed an update and everything is working now.

I'll deploy new versions of terminal services client and server to production (as it is backwards compatible) tomorrow.

**Comment by mjtko** [comment]
Working now.
