### ISSUE TITLE
Send logs to cluster-specific channel

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#689]
As well as sending log notifications to the #support channel, also send them to an additional channel configured against the cluster.

Channel should be optional so they can be disabled if we want/need to without code changes.

**Comment by jamesremuscat** [comment]
Note that:

> You **cannot override** the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration. ([source](https://api.slack.com/incoming-webhooks))

I think this means that we'll need to configure Slack with additional webhook URLs and store those against clusters, rather than channels.

**Comment by mjtko** [comment]
I think the above is talking about overriding the default fsr, I know for sure that one of our webhooks is configured to post to #test, but it posts to a different channel.

**Comment by jamesremuscat** [comment]
@atoghill politely tells me I'm completely wrong so disregard that comment!
