### ISSUE TITLE
Reopen case comments field should include usual markdown enhancements

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#703]
When a case is reopened the modal that displays the comment box doesn't accept Markdown in the textarea shown.  As this is adding a comment, for consistency, it should allow Markdown.

**Comment by jamesremuscat** [comment]
For clarity: the textarea for reopening a case does _allow_ Markdown, but doesn't yet offer the preview or syntax guide functionality that other Md fields do, so it's not obvious that it does.
