### ISSUE TITLE
Add "Comment and resolve" button

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#709]
With the new case resolution workflow, it's commonplace to add a comment then resolve a case in two clicks.  This also generates two emails/slack notifications.

Ideally, we'd have a "comment and resolve" button that both added the comment and marked the case as closed with only one resultant email/slack notification.

**Comment by mjtko** [comment]
I think we should bump the priority of this and deal with this sooner rather than later to reduce the quantity of unnecessary/quick-succession emails.

**Comment by jamesremuscat** [comment]
Fixed by #764 and #767.

**Comment by mjtko** [comment]
Reopening to remind us to split out bits that aren't fixed by #764, #767 and #790 (which I think is just the removal/replacement of multiple Slack notifications bit).

**Comment by benarmston** [comment]
New ticket opened to track the only outstanding part of this issue.
