### ISSUE TITLE
Roll gravatars out to other appropriate places within UI

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#711]
Currently we show gravatars against engineer and site contact names on the case list, but don't make use of them elsewhere.

We should add them in other appropriate places in the UI for consistency and to make use of the visual cues they provide.

Also maybe add them to the HTML emails where appropriate.

**Comment by jamesremuscat** [comment]
Fixed by #929 (and work leading up to it, as detailed above).
