### ISSUE TITLE
Allow editing/creating issue tiers without requiring hotfix/data migration

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#714]
Currently the admin interface doesn't let us create new issues due to validation constraints.  We should identify why and either update this to stop it from happening, or come up with another means of creating/modifying issues within the system without needing a full redeploy.

Ref: https://alces.slack.com/archives/C72GT476Y/p1538128648000100

**Comment by jamesremuscat** [comment]
This is a consequence of not being able to set `nil` as a value through the `rails-admin` interface.

It submits the empty string for any empty fields, which means that inevitably `fields` and `tool` will both be "present" in the record - which is correctly failing validation.

Quick solution is to force "empty string" to `nil` when setting `tool` and `fields`.

**Comment by jamesremuscat** [comment]
Slight correction to original bug report: issues can be created fine, it's their tiers where this problem lies.
