### ISSUE TITLE
Preserve data in browser that has been entered in daily checks form

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#717]
A couple of times now we've lost all the data that's been entered for daily checks on submit (due to various reasons outside of the control of the FC app itself).

We should preserve data for the daily checks form in local storage in the browser and only clean it up when the data has been verified as being successfully recorded.

**Comment by jamesremuscat** [comment]
A possible alternative would be to allow check results to be submitted individually, or some concept of a "draft" set of check results that can be submitted in part and resumed before being finalised. Not sure of the relative difficulties of implementing these!
