### ISSUE TITLE
Allow editing of Cases by admins

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#72]
I’d like to be able to modify a tickets key details when viewing on overview page (https://center.alces-flight.com/cases/76)

in particular: (for admin only)
category/issue
subject

as a secondary (to discuss implementation of):
service / component / component groups 
add additional comments

whenever anything is changed send out an email via RT to notify of the change

**Comment by bobwhitelock** [comment]
- Editing of issue/category and subject, and adding an RT reply when these are changed, should be relatively straightforward.

- Similarly the secondary goal of changing the service and component should be straightforward and similar to the above.

- Changing to a component group is something we don't currently support; requires further discussion.

- Not sure what adding additional comments would involve, sounds like something we don't currently support (but can be done in RT?); requires further discussion.

**Comment by bobwhitelock** [comment]
From meeting:

- Ignore ComponentGroup part for now (do https://trello.com/c/XU8b6jLU/178-add-support-for-logging-cases-against-groups first).

- Do commenting in https://trello.com/c/hd5shx6u/180-allow-commenting-within-flight-center-on-cases-for-contacts-and-engineers instead.

- Allow editing of other fields as requested in issue.

**Comment by bobwhitelock** [comment]
Trello: https://github.com/alces-software/alces-flight-center/issues/72

**Comment by jamesremuscat** [comment]
Category/issue and subject are the only things from the original list left to implement.

**Comment by jamesremuscat** [comment]
Context: almost all `Issue`s are associated with a particular `ServiceType`. In order for a `Case` to be valid, it must have an association to the `ServiceType` required by its `Issue`.

When editing a `Case`'s `Issue` and/or `Category`, should we:

- Only offer as options those `Issue`s which would be valid for the current set of associated components and services?

or

- Offer all possible `Issue`s, even those that would require a different selection of components and services; then:
  - raise an error so the admin knows he needs to try a bit harder?
  - try to fix it ourselves by trying to guess which service might possibly fulfil the requirements?

(As an aside: we're not currently validating that cases remain valid when their associations change. We should probably do that or else end up with a bunch of invalid cases in the database.)
