### ISSUE TITLE
Compulsory maintenance

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#73]
Allow an admin to override the user confirmation stage when making a maintenance request in exceptional cases

**Comment by bobwhitelock** [comment]
It is currently possible (and will remain possible in the new maintenance system being worked on at the moment unless we add explicit handling to prevent this) for an admin to confirm maintenance themselves. This means an admin can already bypass the user confirmation step of a maintenance request if needed.

Is this sufficient for the initial version of this feature? If not, how should this differ from what is already possible?

**Comment by ste78** [comment]
Yeah thats what's currently happening, but I'm not keen on how it looks, it looks like we are just skipping getting confirmation from the end user - It needs to look more intentional... "Steve Norledge has marked this node down for compulsory maintenance" ie visibly skip the confirmation procedure.

**Comment by bobwhitelock** [comment]
Yep OK, makes sense - do you want the confirmation skipping to happen when initially submitting the maintenance request form or as an extra step once this has been done and the request made on the original ticket (or both)?

**Comment by bobwhitelock** [comment]
Have as checkbox when request maintenance

**Comment by bobwhitelock** [comment]
Start time is then irrelevant; maintenance started as soon as form submitted - could have this selected instead of start date.

**Comment by bobwhitelock** [comment]
This was done in https://github.com/alces-software/alces-flight-center/pull/139.
