### ISSUE TITLE
Error when viewing components list when a cluster has no component groups

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#730]
If a cluster hasn't had any components added, then viewing the components list generates an error.

**Comment by mjtko** [comment]
Turns out this is component groups, not components, cos if I create an empty component group, all is well.  Same holds tho -- should work without any component groups.

**Comment by jamesremuscat** [comment]
Related: https://sentry.io/alces-software-ltd/alces-flight-center/issues/711420219/?environment=production
