### ISSUE TITLE
Cannot create any cases when a cluster has no components

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#731]
When a cluster has no components, the case creation form refuses to render.

The set up process is currently working like this:

1. Create the site (if it doesn't yet exist)
2. Create the cluster with basic information
3. Create change request cases

The hardware list may or may not have been imported by the time we need to perform (3), so the cases form needs to operate without components being created.

**Comment by jamesremuscat** [comment]
When I try this I get the following error message:

```
Error initializing form: I ran into a `fail` decoder at _.clusters[0].components: expected list with more than one element. Please contact support@alces-software.com.
```

@mjtko Is that the same as what you get?

**Comment by mjtko** [comment]
Yup, that's what I got. To work around the problem I've added a dummy component group and dummy component for now.

**Comment by jamesremuscat** [comment]
My thoughts:
- The least surprising/confusing approach would be to only list issues not requiring a component if no components are defined (or display, but disable, those which would require a component if that is easier).
- We're fine to assume the presence of at least one issue
- Likewise fine to assume the presence of at least one service per cluster

Unless @mjtko disagrees with any of that, of course!

**Comment by bobwhitelock** [comment]
Trello: https://trello.com/c/PWoAgtc6/539-cannot-create-any-cases-when-a-cluster-has-no-components
