### ISSUE TITLE
Automatic verification of resolved cases isn't working

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#744]
AFAICS, while the reminder email is being sent, the automatic verification it says it's going to undertake doesn't happen.

See: https://alces.slack.com/archives/C72GT476Y/p1538814705000100

**Comment by mjtko** [comment]
Looks like rather than "at the end of the next working day ([day] at 6pm)", this is happening at 6am on the first business day after that time.

**Comment by jamesremuscat** [comment]
Derp. The crontab was wrong (using 6am rather than 6pm). Now fixed for both staging and production.
