### ISSUE TITLE
Implement hotkeys for setting the result of a check

### ISSUE THREAD

**Issue by atoghill** [alces-software/alces-flight-center#746]
Having hotkeys to assign the result of a check could help massively in reducing the time spent filling out the check result submission form. From a brief investigation we could use something like https://github.com/derekprior/jquery-hotkeys-rails to add hotkey support.

**Comment by benarmston** [comment]
@atoghill could you elaborate on what you want the hotkeys to do?

**Comment by jamesremuscat** [comment]
Implemented by #808 and #814.
