### ISSUE TITLE
Make sure Gmail doesn't thread separate clusters' daily checks emails

### ISSUE THREAD

**Issue by jamesremuscat** [alces-software/alces-flight-center#758]
Gmail is grouping together the "daily checks submitted" emails into one thread.

We probably need to add a disambiguation suffix (per cluster) in the same way we do with cases.

**Comment by benarmston** [comment]
Can I confirm what the desired behaviour for this is:

 1. All daily checks emails for a single cluster are grouped together.
 2. Daily checks for different clusters are not grouped together.
