### ISSUE TITLE
Improve button spacing/appearance

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#769]
Low priority cos admin only, but this doesn't look very attractive IMO:

<img width="496" alt="screenshot 2018-10-15 at 10 30 56" src="https://user-images.githubusercontent.com/206834/46942565-849dab80-d065-11e8-8855-f36a5d919787.png">

**Comment by jamesremuscat** [comment]
:thinking: I'm sure @atoghill and I had a discussion about that, and I'm sure we fixed it already. Perhaps I managed to break it somehow...

**Comment by atoghill** [comment]
Yeah we definitely had them looking like:

![screenshot_2018-10-15 demo7 custom commercial - alces flight center](https://user-images.githubusercontent.com/36155339/46943295-40130f80-d067-11e8-937a-e3a9187cde0c.png)

I think what has happened is that when @jamesremuscat took over from me on that PR after I fell ill some pieces of code got moved around and very slightly changed. From looking at https://github.com/alces-software/alces-flight-center/blob/develop/app/views/cases/_associations.html.erb it looks like the `btn-block` class has been removed from the first two buttons.
