### ISSUE TITLE
Changing field values has become less usable

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#772]
On #396 I suggested "replace ALL the buttons" however, it's now a scroll-and-click operation to, for example, change the assigned engineer and feels less usable. Whoops.

I'm not sure if this is a positioning thing or if we need some/all of the buttons back and make the "update case details" button continue to, well, update ALL the details.

I guess in an ideal world we'd do something clever like have a "tick" button next to each field that only became active when a change was detected and when clicked displayed a spinner and made the change in the background.  We don't live in an ideal world, and that also causes other problems with things like "if I become the engineer then display the comment textarea now".  So that sounds complex.

The "add the buttons back" seems like a compromise that will (a) keep things more usable and (b) prevent people from submitting comments and losing the other things they've changed (primarily time worked).

**Comment by benarmston** [comment]
Having spent some time trying to reorganise the positioning of the elements, I'm no longer convinced that that approach is viable.  The best that I could do is

![image](https://user-images.githubusercontent.com/287050/47012786-06acd380-d13d-11e8-95b9-df2777b98ec1.png)

which still doesn't show the submit button without scrolling.  And in certain circumstances, such as maintenance windows and related cases being present the submit buttons are even further away.

**Comment by mjtko** [comment]
@jamesremuscat: yup, that sounds like the pragmatic solution for now.  And, yup, I'm keen on seeing this page get a lick of paint!

**Comment by jamesremuscat** [comment]
Fixed by #803.
