### ISSUE TITLE
Hex-incompatible emojis are still broken (now more badly) 😱

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#776]
Something's missing and it's causing the hex-incompatible emoji still to be present for selection but to no longer render correctly. 🤔

**Comment by jamesremuscat** [comment]
Looks like `emoji-mart.js` has the aliases hardcoded? Not sure what the original source of that file is (it's clearly been `webpack`ed).

**Comment by mjtko** [comment]
I think that's one of the places the problem occurs, the other being that `preview.js.erb` isn't being recompiled for some reason.  I'll take a look at this.
