### ISSUE TITLE
Site logo too small and causes site name to become truncated

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#783]
The logo needs to be made more impactful.

I've not been able to test the cluster logo yet (#773), but assuming this is implemented in the same way, that will need addressing too.

**Comment by jamesremuscat** [comment]
Other than "larger" do you mean anything in particular by "impactful"?

**Comment by jamesremuscat** [comment]
Before:
![demo site - alces flight center - google chrome_019](https://user-images.githubusercontent.com/3471844/47099923-3ee00f00-d22e-11e8-82de-2d45e1b86f31.png)

WIP:
![demo site - alces flight center - google chrome_020](https://user-images.githubusercontent.com/3471844/47099935-443d5980-d22e-11e8-9901-c13c692b3d29.png)

Heading in the right direction? (Not finished yet...)

**Comment by mjtko** [comment]
Yup, looking better already!

**Comment by jamesremuscat** [comment]
Not sure how I feel about this:
![demo site - alces flight center - google chrome_021](https://user-images.githubusercontent.com/3471844/47103176-8f5b6a80-d236-11e8-910a-208056846151.png)
The site (or cluster) logo will show in that corner for all pages in that site (or cluster)'s dashboard, including credit usage, cluster checks, cases lists.

I've had to do something ugly with the layout markup to make sure the title lines up with the content properly, but it's functional, at least until we overhaul the layout fully.

Thoughts?

**Comment by mjtko** [comment]
Looks nice -- we should concentrate on the logos being square-shaped though, which I think should (maybe?) simplify the design work.
