### ISSUE TITLE
Paginate logs

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#794]
As time has gone on, the number of log entries generated against clusters has increased.  We could now do with adding pagination in a similar vein to the pagination we've added for cases.

Similar to #775, have a default amount of logs that are displayed (most recent N, probably 10) but allow the user to select to view a larger number at once if they would like to.

**Comment by atoghill** [comment]
The last part of this issue was resolved by #844 therefore I am closing this issue.
