### ISSUE TITLE
Informational case workflow

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#801]
When a condition is noticed on a cluster that we want to inform the customer about and/or request them to take action, we open a case.  The current workflow is to open an "other" category case and add a comment in the "Details" field.  We then "wait for a bit" to see if the customer wants/needs to respond, and resolve the case if there is no further action to be taken.

Instead, we'd like:

1. Open an "informational case" which is a tier 3 case, with a "Details" field.
2. Have the case behave as if it's immediately resolved, but with "acknowledge this notice" instead of "the issue is fixed - verify this case" and "request further information" instead of "the issue is not fixed - reopen this case".
3. Customer acknowledges, case becomes verified -or- customer requests more information, case becomes standard open tier 3.

Displaying the case state: as the case isn't really immediately "resolved", it would be preferable to display it with a state of "notice" rather than "resolved".

Handling time worked: we could set this to zero by default though it would be nice to be able to specify an amount of time worked when creating the case.

**Comment by mjtko** [comment]
Usual auto-closure process for resolved but unverified cases should apply.

**Comment by jamesremuscat** [comment]
Thoughts and suggested implementation plan at https://docs.google.com/document/d/1_6H2cO3Kp2CjTW7b0cR2GtFgogOTwPz9PLta1JDcQj4

**Comment by mjtko** [comment]
LGTM, let's go with this plan and iterate on it as and when we discover further requirements.
