### ISSUE TITLE
Improve the copy cluster check command to clipboard feedback

### ISSUE THREAD

**Issue by benarmston** [alces-software/alces-flight-center#816]
It should look nicer.  Perhaps inline with the command? Perhaps smaller? Perhaps greyer; similar to bootstrap form help text?

Refs #811

**Comment by mjtko** [comment]
Can we just flash the command element? Something like one of these?

 https://stackoverflow.com/questions/275931/how-do-you-make-an-element-flash-in-jquery

Having the "Copied!" text permanently stuck on the page doesn't feel right.

**Comment by mjtko** [comment]
Fixed via #820.
