### ISSUE TITLE
Page content width has narrowed

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#818]
Production:

![screenshot 2018-10-19 at 08 56 41](https://user-images.githubusercontent.com/206834/47205152-0ac73400-d37d-11e8-94a9-2a183c4774f1.png)

Dev/staging:

![screenshot 2018-10-19 at 08 56 39](https://user-images.githubusercontent.com/206834/47205164-1155ab80-d37d-11e8-8d7b-6e1a339b19dd.png)

**Comment by jamesremuscat** [comment]
Yes, this was done as part of #807 to ensure that the main content and page title are in line.

In my browsers there's still enough room for all the "tabs" entries on a single line, and by some distance - I'm not sure why that isn't the case for you (which is, I assume, the trigger for this being a release-blocking problem?):

![cases - demo cluster - alces flight center - google chrome_030](https://user-images.githubusercontent.com/3471844/47207382-07cf4200-d383-11e8-9dd2-f2f76603f5cb.png)

We can either:
- Widen the content and have the title not line up
- Widen the content and shrink the area available to the logo to make the title line up

Do you have a preference?

**Comment by mjtko** [comment]
Yup, this is possibly cos I don't use my browser maximized -- at the width I tend to use there is now a lot more whitespace.  Having said that, when I go full maximized, there is now less whitespace (which is great!).

Tho I can't imagine quite how it looks, I think I'd sacrifice the lining up of the title to increase the amount of screen real estate being used at this slightly narrower width.  Do I have to compromise on what happens at the maximum (1920ish I think) width if we do this tho?

**Comment by jamesremuscat** [comment]
Here's the diff for the first option - it should be straightforward for you to apply using Chrome dev tools (just change four numbers!) and let me know what you think:

```diff
@@ -57,8 +57,8 @@
 
         <% if flash.any? %>
           <div class="row">
-            <div class="col-2 d-none d-lg-block"></div>
-              <div class="col-12 col-lg-8">
+            <div class="col-1 d-none d-lg-block"></div>
+              <div class="col-12 col-lg-10">
                 <%= render 'partials/flash_alert', flash_key: :alert, alert_class: 'alert-danger' %>
                 <%= render 'partials/flash_alert', flash_key: :error, alert_class: 'alert-danger' %>
                 <%= render 'partials/flash_alert', flash_key: :success, alert_class: 'alert-success' %>
@@ -68,8 +68,8 @@
         <% end %>
 
         <div class="row">
-          <div class="col-2 d-none d-lg-block"></div>
-          <div class="col-12 col-lg-8">
+          <div class="col-1 d-none d-lg-block"></div>
+          <div class="col-12 col-lg-10">
             <%= yield %>
           </div>
         </div>
```
