### ISSUE TITLE
Some emails are being sent to site contacts that shouldn't be

### ISSUE THREAD

**Issue by atoghill** [alces-software/alces-flight-center#851]
Emails for the following are being sent to site contacts since `2018.9`:
* Assigned engineer change
* Issue change

This is because the conditionals within the `update_email_recipients` method of the `CaseMailer` do not take into account that the `:updated_at` field will also change with these case updates.

**Comment by mjtko** [comment]
Seems like this should probably be hotfixed as a regression.
