### ISSUE TITLE
Last updated time of case can be updated without engineering involvement

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#860]
It seems that there is an event that can cause the last updated time on a case to be updated without an engineer performing an action.

See https://alces.slack.com/archives/C72GT476Y/p1540640848001500 for more details.

**Comment by jamesremuscat** [comment]
Confirmed that site contacts setting the assigned contact for a case causes that case's `last_updated` to be changed.

A site contact adding a comment leaves the `last_updated` value unchanged, as expected.

**Comment by mjtko** [comment]
Also seems to happen with verification reminder emails.

**Comment by jamesremuscat** [comment]
@mjtko Already raised as #745.
