### ISSUE TITLE
Preserve comment text when failing to add when there's a pending update

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#875]
> Your changes could not be saved as there are already pending changes for this case.

This is fair enough, but if I've not noticed (cos I'm half asleep on a Monday morning) then I could end up losing a carefully crafted comment.

Can the comment text be preserved in this case please?  Then I would have the opportunity to copy it before cancelling the existing update, then repasting.

**Comment by mjtko** [comment]
Or it might be better to suppress the comment box in this situation?

**Comment by benarmston** [comment]
Should we not be suppressing all of the form elements?

**Comment by mjtko** [comment]
Not concerned about the others, cos the changes are not as hard to reproduce.

**Comment by benarmston** [comment]
This was fixed by #890.
