### ISSUE TITLE
Copy change: "deferred until"

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#877]
> This change has been deferred until Mon 5th Nov 10:24

This feels a bit clunky in the "normal buffered" case (I understand the language probably arose when considering the scheduling outside of business hours feature).

Can we update this to say:

"Unless cancelled, this update will be applied at Mon 5th Nov 10:24"

**Comment by mjtko** [comment]
I hadn't spotted this message in the web UI, and was referring to the Slack message - can we change that too please?

**Comment by benarmston** [comment]
Will do.
