### ISSUE TITLE
Difficult to copy buffered comment

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#879]
Due to markdown rendering, it is difficult to copy a buffered comment.  Use case:

Engineer has written an in depth comment and spotted a typo.  Wants to copy/cancel/paste/resubmit update.

<img width="984" alt="screenshot 2018-11-05 at 10 32 41" src="https://user-images.githubusercontent.com/206834/47992926-26a13880-e0e6-11e8-85a4-3e1148cd6f9e.png">

Perhaps the comment could be rendered without rendering its markdown internally? i.e. shove it in a codefence, and escape?

**Comment by mjtko** [comment]
Also, the rendered markdown of the comment can break the rendering of the card in general -- see "User" field in the above screenshot.

**Comment by jamesremuscat** [comment]
I think we're probably going to need to special-case comments when generating the summary of changes.
