### ISSUE TITLE
Better handling of case update notifications for "minor" events

### ISSUE THREAD

**Issue by benarmston** [alces-software/alces-flight-center#901]
Some changes to an event, such as changing the time worked or engineering level, send a strange set of slack notifications.  

 - The change itself does not produce a slack notification as it is considered minor.
 - There is a notification about a deferred change having been made.
 - There is a notification if the deferred change is manually applied or cancelled.

The following screenshot perhaps illustrates this better.   Here I added some time worked to the case, yet it is never mentioned in a slack notification.

![image](https://user-images.githubusercontent.com/287050/48059154-4d2ba600-e1b0-11e8-9c89-070fba6f07a4.png)

Possible solutions:

 - Don't send any slack notifications for "minor" changes.
 - Send slack notifications for all changes, even "minor" ones.

**Comment by benarmston** [comment]
@mjtko @jamesremuscat do you have a preference between the two possible solutions?

**Comment by jamesremuscat** [comment]
"Don't send any Slack notifications for minor changes" would be consistent with emails, where we examine a subset of the possibly changed fields to determine if we want to send an email at all.
